# Generated by Django 4.2.9 on 2024-08-03 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmis', '0002_client_first_name_client_last_name_task_assigned_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': (('can_assign_task_to_client', 'Can Assign Task to Client'),)},
        ),
    ]
