# Generated by Django 4.2.9 on 2024-08-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmis', '0004_project_image_2_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
