# Generated by Django 4.2.9 on 2024-08-18 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmis', '0005_project_budget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task',
            new_name='name',
        ),
    ]
